#!/usr/bin/env python3
# Stellarium Web Engine
#
# Build the OFFLINE DSS deep-sky imaging layer (HiPS orders 3-4) shipped in the
# repo, so the "DSS" background works with no network. The public CDS survey at
# data.stellarium.org/surveys/dss stores tiles only from order 3 up; we download
# the full-res Norder3 (768) + Norder4 (3072) tiles and re-encode them at webp
# quality 90 (VP8 lossy, ~8% smaller than the CDS originals, visually lossless).
#
# Orders shipped: 3-4 full-res (downloaded + re-encoded here) PLUS a low-res
# order-2 FALLBACK BASE generated by make-dss-lowres.py (called at the end of
# main). Order 2 is NOT for detail -- DSS is FOV-gated in src/modules/dss.c and
# the visible detail is order 3-4. Order 2 is the coarse base that the fallback
# chain (4->3->2) draws while finer tiles are still loading, so a newly zoomed/
# panned region never flashes BLACK now that the Milky Way backdrop fades out by
# ~25 deg FOV. make-dss-lowres.py also lowers hips_order_min to 2 in properties
# (data-driven, no WASM rebuild). Orders 0-1 are still dropped (order 2 is enough
# of a base; a true always-resident allsky would need order_min=0). hips_order=4
# caps requests so the engine never asks for missing deeper tiles. Orders 5-6
# would add ~500 MB / ~1.2 GB (impractical offline); to go deeper raise MAX_ORDER.
#
# Output: apps/skydata/surveys/dss/{properties, Norder{3,4}/Dir0/Npix*.webp}
#         (~68 MB)
#
# Requires the libwebp CLI (cwebp/dwebp) for the Q90 re-encode:
#   python3 tools/make-dss-survey.py
# Uses a download cache under $TMPDIR (re-run is incremental).

import os
import shutil
import subprocess
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "apps", "skydata", "surveys", "dss")
SRC = "https://data.stellarium.org/surveys/dss"        # CDS DSS2 color mirror
CACHE = os.path.join(os.environ.get("TMPDIR", "/tmp"), "swe-dss-cache")
MIN_ORDER = 3     # lowest order shipped (= base; DSS never renders below this)
MAX_ORDER = 4     # highest order shipped
Q = 90            # webp re-encode quality (visually lossless, ~8% smaller)


def reencode(src, dst, q):
    """Re-encode a webp tile at quality q (method 6). Returns True on success."""
    dec = subprocess.run(["dwebp", "-quiet", "-pam", src, "-o", "-"],
                         capture_output=True)
    if dec.returncode != 0:
        return False
    enc = subprocess.run(["cwebp", "-quiet", "-q", str(q), "-m", "6",
                          "-o", dst, "--", "-"], input=dec.stdout,
                         capture_output=True)
    return enc.returncode == 0


def fetch(rel, dst):
    if os.path.exists(dst) and os.path.getsize(dst) > 0:
        return True
    try:
        with urllib.request.urlopen(f"{SRC}/{rel}", timeout=60) as r:
            data = r.read()
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(dst, "wb") as f:
            f.write(data)
        return True
    except Exception as e:
        print(f"  miss {rel}: {e}")
        return False


def cache_path(order, p):
    return os.path.join(CACHE, f"Norder{order}", f"Dir{p // 10000}", f"Npix{p}.webp")


def download_order(order):
    n = 12 * 4 ** order
    print(f"downloading Norder{order} ({n} tiles, cached) ...")
    have = 0
    for p in range(n):
        rel = f"Norder{order}/Dir{p // 10000}/Npix{p}.webp"
        if fetch(rel, cache_path(order, p)):
            have += 1
    print(f"  have {have}/{n}")
    return have


PROPERTIES = """hips_order            = {maxo}
hips_order_min        = {mino}
hips_tile_width       = 512
hips_tile_format      = webp jpeg
dataproduct_type      = image
hips_frame            = equatorial
obs_title             = DSS colored (offline {mino}-{maxo})
hips_release_date     = 2026-07-09T00:00:00Z
hips_version          = 1.31
obs_copyright         = Digitized Sky Survey - STScI/NASA, Colored & Healpixed by CDS
obs_copyright_url     = http://archive.stsci.edu/dss/copyright.html
obs_description       = DSS2 color HiPS, offline subset (orders {mino}-{maxo}, re-encoded at webp Q90), from the CDS tiles hosted at data.stellarium.org/surveys/dss.
creator_did           = ivo://CDS/P/DSS2/color
"""


def main():
    for o in range(MIN_ORDER, MAX_ORDER + 1):
        if download_order(o) < 0.9 * 12 * 4 ** o:
            sys.exit(f"too few order-{o} tiles; aborting")

    # Ship a clean tree: remove any stale lower-order dirs from earlier builds.
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    print(f"re-encoding orders {MIN_ORDER}-{MAX_ORDER} at Q{Q} ...")
    for order in range(MIN_ORDER, MAX_ORDER + 1):
        n = 12 * 4 ** order
        for p in range(n):
            src = cache_path(order, p)
            if not os.path.exists(src):
                continue
            dst = os.path.join(OUT, f"Norder{order}", f"Dir{p // 10000}",
                               f"Npix{p}.webp")
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            if not reencode(src, dst, Q):
                sys.exit(f"re-encode failed for order {order} Npix{p}")

    with open(os.path.join(OUT, "properties"), "w") as f:
        f.write(PROPERTIES.format(mino=MIN_ORDER, maxo=MAX_ORDER))

    # Add the low-res order-2 fallback base (downsampled from the order-3 tiles
    # just written) and lower hips_order_min to 2. Keeps a single-command
    # rebuild consistent: without this, re-running would wipe Norder2 (rmtree
    # above) and reset order_min to 3, reintroducing the black-hole-on-load bug.
    print("adding low-res fallback base (order 2) ...")
    subprocess.run([sys.executable, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "make-dss-lowres.py")],
        check=True)

    total = sum(os.path.getsize(os.path.join(r, fn))
                for r, _, fs in os.walk(OUT) for fn in fs)
    print(f"wrote orders 2-{MAX_ORDER} -> {OUT}  ({total/1e6:.0f} MB)")


if __name__ == "__main__":
    main()
