#!/usr/bin/env python3
# Stellarium Web Engine
#
# Subset the Material Design Icons webfont down to the icons the frontend
# actually uses, so the app stops shipping the full ~404 KB woff2 (+ ~350 KB
# of icon CSS). Output is a few-KB woff2 + a minimal CSS with only the used
# `.mdi-*::before` rules; class-based usage in the components is unchanged.
#
# The icon list is collected automatically from:
#   - `mdi-*` names referenced in the src/ of both frontends
#     (apps/web-frontend and apps/web-frontend-app), and
#   - Vuetify's internal mdi alias set (checkboxes, menus, ratings, ...),
#     node_modules/vuetify/lib/iconsets/mdi.js
# so re-run this after adding icons to components or upgrading Vuetify.
# One union subset is written into both trees (the app tree's `npm run build`
# runs this as `prebuild`; it used to write only into apps/web-frontend and the
# app tree kept shipping a stale copy).
#
# Usage: tools/make-mdi-subset.py   (needs fonttools + brotli)
# Output: apps/web-frontend{,-app}/src/assets/mdi/mdi-subset.woff2 + mdi-subset.css

import logging
import os
import re
import sys

from fontTools import subset

# @mdi/font's TTF trips two harmless loader warnings (post.stringData padding,
# pre-1904 timestamps). subset.main() used to hide them; keep the build log quiet.
logging.getLogger("fontTools").setLevel(logging.ERROR)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Both frontend trees; a tree that is absent (e.g. after the standard tree is
# retired) is simply skipped.
FRONTS = [d for d in (os.path.join(ROOT, "apps", "web-frontend"),
                      os.path.join(ROOT, "apps", "web-frontend-app"))
          if os.path.isdir(os.path.join(d, "src"))]
# node_modules come from whichever tree has them installed (the app tree first:
# it is the one whose build invokes this script).
_NM = next((os.path.join(d, "node_modules") for d in reversed(FRONTS)
            if os.path.isdir(os.path.join(d, "node_modules", "@mdi", "font"))),
           None)
if _NM is None:
    sys.exit("@mdi/font not found in any frontend's node_modules (npm install first)")
MDI = os.path.join(_NM, "@mdi", "font")
VUETIFY_ALIASES = os.path.join(_NM, "vuetify", "lib", "iconsets", "mdi.js")
OUT_DIRS = [os.path.join(d, "src", "assets", "mdi") for d in FRONTS]

BASE_CSS = """\
/* Generated by tools/make-mdi-subset.py — do not edit.
   Subset of @mdi/font (Apache-2.0, https://pictogrammers.com) with only the
   icons this app uses. Re-run the script after adding icons. */
@font-face {
  font-family: "Material Design Icons";
  src: url("./mdi-subset.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
}
.mdi:before,
.mdi-set {
  display: inline-block;
  font: normal normal normal 24px/1 "Material Design Icons";
  font-size: inherit;
  text-rendering: auto;
  line-height: inherit;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.mdi-spin:before {
  animation: mdi-spin 2s infinite linear;
}
@keyframes mdi-spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
"""


def used_names():
    names = set()
    for front in FRONTS:
        for base, _, files in os.walk(os.path.join(front, "src")):
            for fn in files:
                if not fn.endswith((".vue", ".js")):
                    continue
                text = open(os.path.join(base, fn), encoding="utf-8",
                            errors="ignore").read()
                names.update(re.findall(r"\bmdi-[a-z0-9-]+\b", text))
    names.update(re.findall(r"\bmdi-[a-z0-9-]+\b",
                            open(VUETIFY_ALIASES, encoding="utf-8").read()))
    names.discard("mdi-set")     # CSS helper class, not an icon
    names.discard("mdi-spin")    # CSS animation class, not an icon
    names.discard("mdi-subset")  # this tool's own output files, not an icon
    return sorted(names)


def css_codepoints():
    """icon name -> codepoint, parsed from the full @mdi/font css."""
    css = open(os.path.join(MDI, "css", "materialdesignicons.css"),
               encoding="utf-8").read()
    cps = {}
    for m in re.finditer(
            r'\.(mdi-[a-z0-9-]+)::?before\s*{\s*content:\s*"\\+([0-9A-Fa-f]+)"',
            css):
        cps[m.group(1)] = int(m.group(2), 16)
    return cps

def main():
    names = used_names()
    cps = css_codepoints()
    missing = [n for n in names if n not in cps]
    if missing:
        sys.exit("icon names with no codepoint in @mdi/font css: %s" % missing)
    unicodes = sorted(cps[n] for n in names)
    print("subsetting %d icons" % len(names))

    # Programmatic subsetter, not subset.main([...]): main() only *logs* a bad
    # option and returns, so a typo (this script shipped `--no-recalc-timestamps`
    # for weeks) silently left the old woff2 in place while the build went green.
    # Options.parse_opts raises on anything unknown, and the save below raises
    # if the font could not be written.
    options = subset.Options()
    options.parse_opts([
        "--no-hinting", "--glyph-names=0", "--layout-features=",
        "--no-recalc-timestamp",  # keep the font's own timestamp: reproducible bytes
        "--flavor=woff2",
    ])
    font = subset.load_font(
        os.path.join(MDI, "fonts", "materialdesignicons-webfont.ttf"), options)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)

    rules = "".join('.%s::before { content: "\\%X"; }\n' % (n, cps[n])
                    for n in names)
    for out_dir in OUT_DIRS:
        os.makedirs(out_dir, exist_ok=True)
        woff2 = os.path.join(out_dir, "mdi-subset.woff2")
        subset.save_font(font, woff2, options)
        if not os.path.getsize(woff2):
            sys.exit("subset produced an empty font: %s" % woff2)
        css_path = os.path.join(out_dir, "mdi-subset.css")
        open(css_path, "w", encoding="utf-8").write(BASE_CSS + rules)
        print("  %s: %.1f KB" % (woff2, os.path.getsize(woff2) / 1024.0))
        print("  %s: %.1f KB (%d rules)" % (css_path,
              os.path.getsize(css_path) / 1024.0, len(names)))


if __name__ == "__main__":
    main()
